INSERT INTO soundbox.genres (`id`, `name`) VALUES ('1', 'Alternative Rock')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('2', 'Ambient')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('3', 'Classical')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('4', 'Country')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('5', 'Dance & EDM')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('6', 'Dancehall')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('7', 'Deep House')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('8', 'Disco')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('9', 'Drum & Bass')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('10', 'Dubstep')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('11', 'Electronic')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('12', 'Folk & Singer-Songwriter')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('13', 'Hip-hop & Rap')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('14', 'House')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('15', 'Indie')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('16', 'Jazz & Blues')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('17', 'Latin')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('18', 'Metal')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('19', 'Piano')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('20', 'Pop')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('21', 'R&B & Soul')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('22', 'Reggae')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('23', 'Reggaeton')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('24', 'Rock')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('25', 'Soundtrack')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('26', 'Techno')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('27', 'Trance')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('28', 'Trap')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('29', 'Triphop')
INSERT INTO soundbox.genres (`id`, `name`) VALUES ('30', 'World')