INSERT INTO domination.user (`id`, `email`, `name`, `password`) VALUES (1, 'root', 'Manu', 'abcd')
INSERT INTO domination.favorites ( `user_email`, `artist_id`, `user_id`) VALUES ('root', '22409434', 1 )
INSERT INTO domination.favorites ( `user_email`, `artist_id`, `user_id`) VALUES ('root', '36960179', 1 )
INSERT INTO domination.favorites ( `user_email`, `artist_id`, `user_id`) VALUES ('root', '44513723', 1 )
INSERT INTO domination.favorites ( `user_email`, `artist_id`, `user_id`) VALUES ('root', '8145658', 1 )